version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    ports:
      - "7860:7860/udp"
      - "49152:49152/udp"
    runtime: nvidia
    env_file:
      - .env 
    command: >
      bash -c "python -m videollava.serve.video_llava_server --output /app/videollava/serve/output.mp4 --model-path 'LanguageBind/Video-LLaVA-7B' --load-4bit"